jenkins:
  systemMessage: "YAS Jenkins managed by JCasC"
  numExecutors: 0
  mode: NORMAL

  clouds:
    - kubernetes:
        name: "kubernetes"
        namespace: "${JENKINS_NAMESPACE}"
        serverUrl: "https://kubernetes.default.svc"
        jenkinsUrl: "http://${JENKINS_RELEASE_NAME}.${JENKINS_NAMESPACE}.svc.cluster.local:8080"
        jenkinsTunnel: "${JENKINS_RELEASE_NAME}-agent.${JENKINS_NAMESPACE}.svc.cluster.local:50000"
        containerCapStr: "10"

        templates:

          # ======================
          # DEFAULT AGENT
          # ======================
          - name: "default"
            namespace: "${JENKINS_NAMESPACE}"
            label: "k8s-default"
            serviceAccount: "jenkins-deployer"
            nodeUsageMode: NORMAL
            workspaceVolume:
              emptyDirWorkspaceVolume: {}

            containers:
              - name: "jnlp"
                image: "docker.io/hnaht277/jenkins-agent-k8s:0.1"
                alwaysPullImage: true
                workingDir: "/home/jenkins/agent"
                resourceRequestCpu: "100m"
                resourceRequestMemory: "256Mi"
                resourceLimitCpu: "500m"
                resourceLimitMemory: "1024Mi"

          # ======================
          # KANIKO AGENT
          # ======================
          - name: "kaniko-agent"
            namespace: "${JENKINS_NAMESPACE}"
            label: "kaniko"
            serviceAccount: "jenkins-deployer"
            nodeUsageMode: NORMAL

            workspaceVolume:
              emptyDirWorkspaceVolume: {}

            containers:
              - name: "jnlp"
                image: "docker.io/hnaht277/jenkins-agent-k8s:0.1"
                alwaysPullImage: true
                workingDir: "/home/jenkins/agent"

              - name: "kaniko"
                image: "gcr.io/kaniko-project/executor:v1.23.2-debug"
                ttyEnabled: true