hostname: &hostname grafana.yas.local.com
prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
grafana:
  grafana.ini:
    database:
      type: postgres
      host: postgresql.postgres:5432
      name: grafana
      user: yasadminuser
      password: $__env{GF_DATABASE_PASSWORD}
      ssl_mode: require
  adminUser: admin
  adminPassword: $__env{GF_ADMIN_PASSWORD}
  envFromSecret: grafana-secrets
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - *hostname
